spring:
  profiles:
    active: local
  application:
    name: my-blogs
server:
  port: 8888
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0