spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project-name?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&autoReconnectForPools=true
    username: username
    password: password